// ─────────────────────────────────────────────────────────────
// SABIL AHMAD PORTFOLIO — ALL CONTENT & DATA
// ─────────────────────────────────────────────────────────────

export const SITE = {
  name: "Sabil Ahmad",
  title: "CTO & Blockchain Engineer",
  tagline: "Building the Infrastructure of Tomorrow.",
  subTagline: "Blockchain architect. AI product engineer. Venture founder.",
  description:
    "CTO at FANN. Blockchain architect, AI product engineer, and venture founder. 60+ shipped products, 25+ smart contracts deployed across 4 chains, 5 live startups. Based in Doha, Qatar.",
  url: "https://sabilahmad.com",
  email: "Info@sabilahmad.com",
  whatsapp: "97450389351",
  location: "Doha, Qatar",
  locationFull: "Doha, Qatar · Open to remote globally",
  availability: true,
  github: "https://github.com/sabilahmad77",
  linkedin: "https://linkedin.com/in/sabilahmad",
  twitter: "https://x.com/SabilAhmad77",
  medium: "https://medium.com/@sabilkhattak77",
  currentRole: "Chief Technology Officer · FANN",
  currentLocation: "Doha, Qatar",
};

export const STATS = [
  { value: "60+", label: "Projects Delivered" },
  { value: "25+", label: "Smart Contracts" },
  { value: "5+", label: "Startups Launched" },
  { value: "4+", label: "Chains Deployed" },
];

// ─── VENTURES (My Startups) ──────────────────────────────────
export const VENTURES_FEATURED = [
  {
    id: "fann",
    name: "FANN",
    tagline: "The Verified Art Marketplace",
    status: "Live",
    statusColor: "emerald" as const,
    category: "Art Tech · Blockchain · AI/ML",
    logo: "/logos/fann.svg",
    url: "https://fann.art",
    tryfann: "https://tryfann.com",
    role: "Chief Technology Officer",
    period: "Aug 2024 – Present",
    location: "Doha, Qatar",
    description:
      "Art is a multi-trillion-dollar asset class with a provenance problem. FANN solves it: blockchain-verified ownership records, AI-powered valuation, and AR previews — all native to the GCC market. I architect the entire technical foundation.",
    shortDescription:
      "Blockchain-native art marketplace redefining how physical art is owned, verified, and traded in the GCC.",
    achievements: [
      "Leading technical strategy for RWA & ArtTech fractional ownership platform",
      "Architected comprehensive blockchain infrastructure for art authentication",
      "Developed AI-powered valuation systems for digital and physical art assets",
      "Built AR preview system for physical art works",
    ],
    stack: ["React", "Node.js", "Solidity", "IPFS", "AI/ML", "Web3"],
    highlight: true,
  },
  {
    id: "principal-desk",
    name: "Principal Desk",
    tagline: "School Management, Reimagined",
    status: "Live",
    statusColor: "emerald" as const,
    category: "EdTech · SaaS",
    logo: "/logos/principal-desk.svg",
    url: "https://principaldesk.com",
    role: "Founder & CTO",
    period: "Founded",
    location: "GCC / MENA",
    description:
      "Educational institutions run on spreadsheets and group chats. Principal Desk replaces both — unified parent communication, academic tracking, and administration in one platform built for the MENA region.",
    shortDescription:
      "Comprehensive school management platform for educational institutions with integrated communication tools.",
    achievements: [
      "Real-time parent-teacher messaging system",
      "Automated grade reporting and academic tracking",
      "Multi-school SaaS architecture",
      "Integrated payment and scheduling systems",
    ],
    stack: ["React", "Node.js", "PostgreSQL", "Socket.io", "Redis"],
    highlight: true,
  },
];

export const VENTURES_MINI = [
  {
    id: "blockchain-explorer",
    name: "Blockchain Explorer",
    status: "Live",
    url: "https://blockchainexplorer.info",
    description: "Advanced multi-chain blockchain explorer with real-time analytics and smart contract analysis.",
    stack: ["React", "Node.js", "GraphQL", "Web3.js"],
    category: "Developer Tools",
  },
  {
    id: "scan-halal-ai",
    name: "Scan Halal AI",
    status: "Live",
    url: "https://scanhalalai.com/",
    description: "AI-powered halal food verification app using computer vision and Islamic jurisprudence.",
    stack: ["React Native", "Python", "TensorFlow", "Computer Vision"],
    category: "Food Tech · Islamic Tech",
  },
  {
    id: "salesicon",
    name: "Salesicon",
    status: "Live",
    url: "https://salesicon.store",
    description: "AI-powered sales intelligence platform providing real-time insights and automation for sales teams.",
    stack: ["React", "Python", "TensorFlow", "PostgreSQL"],
    category: "SaaS · Sales Tech",
  },
  {
    id: "socicart",
    name: "SociCart",
    status: "Soon",
    url: "#",
    description: "Social commerce platform that transforms shopping into a collaborative and interactive experience.",
    stack: ["React", "Node.js", "MongoDB", "Socket.io"],
    category: "E-commerce · Social",
  },
];

// ─── FEATURED PROJECTS (Client Work) ────────────────────────
export const PROJECTS = [
  {
    id: "mexc-crypto",
    name: "MEXC Crypto",
    description: "Advanced cryptocurrency trading platform with professional-grade tools and gold mining investment operations.",
    longDescription: "Full-featured cryptocurrency trading platform with real-time WebSocket price feeds, portfolio analytics, and DeFi integrations.",
    status: "Live",
    featured: true,
    category: ["DeFi & Tokenisation", "Fintech"],
    stack: ["React", "Node.js", "WebSocket", "MongoDB", "Redis", "Web3.js"],
    image: "/projects/mexc.jpg",
    url: "#",
  },
  {
    id: "nftyart",
    name: "NFTyART",
    description: "NFT marketplace platform for digital art creation, trading, and community building with full Web3 integration.",
    longDescription: "Production-grade NFT marketplace with IPFS storage, smart contract minting, and community governance.",
    status: "Live",
    featured: true,
    category: ["Blockchain & Web3", "Marketplace"],
    stack: ["React", "Solidity", "IPFS", "Web3.js", "Node.js", "MongoDB"],
    image: "/projects/nftyart.jpg",
    url: "#",
  },
  {
    id: "bitxgold",
    name: "BITXGOLD",
    description: "Gold-backed token ecosystem with 1:1 bullion tokenization and full DeFi integration.",
    longDescription: "RWA tokenization platform for gold assets, with on-chain proof of reserves and yield-bearing vaults.",
    status: "Live",
    featured: true,
    category: ["DeFi & Tokenisation"],
    stack: ["MongoDB", "Express", "React", "Node.js", "Solidity", "Hardhat", "Chainlink"],
    image: "/projects/bitxgold.jpg",
    url: "#",
  },
  {
    id: "gold-smart-chain",
    name: "Gold Smart Chain",
    description: "Private permissioned blockchain for compliant gold tokenization with L2 bridges.",
    longDescription: "Enterprise-grade permissioned chain built on Geth with custom consensus, L2 bridge infrastructure, and compliance modules.",
    status: "Production",
    featured: true,
    category: ["DeFi & Tokenisation"],
    stack: ["MongoDB", "Express", "React", "Node.js", "Geth", "Solidity"],
    image: "/projects/gold-smart-chain.jpg",
    url: "#",
  },
  {
    id: "leet-swap",
    name: "LEET Swap",
    description: "Gas-optimized DEX with pro-mode charting and gamer-centric LP incentives.",
    longDescription: "Uniswap v3 fork with custom fee tiers, gamified liquidity mining, and integrated TradingView charts.",
    status: "Live",
    featured: true,
    category: ["DeFi & Tokenisation"],
    stack: ["React", "Solidity", "Uniswap v3 SDK", "The Graph", "Ethers.js"],
    image: "/projects/leet-swap.jpg",
    url: "#",
  },
  {
    id: "allocate",
    name: "Allocate",
    description: "Decentralized crowdfunding platform with milestone-based fund release and DAO governance.",
    longDescription: "Web3 crowdfunding protocol with escrow-gated milestones, multi-sig governance, and on-chain reporting.",
    status: "Live",
    featured: false,
    category: ["DeFi & Tokenisation"],
    stack: ["MongoDB", "Express", "React", "Node.js", "Solidity", "OpenZeppelin"],
    image: "/projects/allocate.jpg",
    url: "#",
  },
  {
    id: "babyloan",
    name: "BABYloan",
    description: "Mobile-first micro-lending platform for crypto-collateralized stablecoin loans.",
    longDescription: "DeFi lending protocol with automated liquidation, risk scoring, and mobile-optimized UX.",
    status: "Beta",
    featured: false,
    category: ["DeFi & Tokenisation"],
    stack: ["MongoDB", "Express", "React", "Node.js", "Solidity", "Chainlink"],
    image: "/projects/babyloan.jpg",
    url: "#",
  },
  {
    id: "cex-arbitrage",
    name: "CEX Arbitrage",
    description: "Low-latency arbitrage bot monitoring price spreads across major centralized exchanges.",
    longDescription: "High-frequency trading bot with sub-50ms order execution, multi-exchange API management, and risk controls.",
    status: "Live",
    featured: false,
    category: ["DeFi & Tokenisation"],
    stack: ["Node.js", "TypeScript", "CCXT", "Redis", "WebSocket"],
    image: "/projects/cex-arb.jpg",
    url: "#",
  },
  {
    id: "midnight-trades",
    name: "MidNightTrades",
    description: "Dark-themed NFT marketplace for nightclub-inspired art with real-time bidding.",
    longDescription: "Niche NFT marketplace with live auction engine, artist royalty enforcement, and curated drops.",
    status: "Live",
    featured: false,
    category: ["NFT Marketplaces"],
    stack: ["MongoDB", "Express", "React", "Node.js", "Solidity", "Socket.io"],
    image: "/projects/midnight.jpg",
    url: "#",
  },
  {
    id: "bleney",
    name: "Bleney NFT Marketplace",
    description: "Generative art NFT hub with lazy minting and fractional ownership vaults.",
    longDescription: "Next.js-powered NFT platform with gasless minting via EIP-2771, The Graph indexing, and fractional vault contracts.",
    status: "Live",
    featured: false,
    category: ["NFT Marketplaces"],
    stack: ["Next.js", "Solidity", "The Graph", "IPFS", "Ethers.js"],
    image: "/projects/bleney.jpg",
    url: "#",
  },
  {
    id: "riseabove",
    name: "RISEABOVE",
    description: "DAO-powered creator toolkit with AR preview and tokenized community governance.",
    longDescription: "NFT platform with Snapshot.org governance integration, on-chain voting, and experimental AR artwork preview.",
    status: "Live",
    featured: false,
    category: ["NFT Marketplaces"],
    stack: ["Next.js", "Solidity", "IPFS", "Snapshot.org", "Ethers.js"],
    image: "/projects/riseabove.jpg",
    url: "#",
  },
  {
    id: "solana-dapp",
    name: "Solana DApp",
    description: "High-APY yield farming protocol with auto-compounding vaults on Solana.",
    longDescription: "Anchor-based DeFi protocol on Solana with automated compound strategies and liquidity mining.",
    status: "Live",
    featured: false,
    category: ["DApps & GameFi"],
    stack: ["React", "Anchor", "Rust", "Solana Web3.js", "TypeScript"],
    image: "/projects/solana.jpg",
    url: "#",
  },
  {
    id: "teen-patti",
    name: "TeenPatti DApp",
    description: "Blockchain-based card game with provably fair randomness and NFT integration.",
    longDescription: "Fully on-chain card game with Chainlink VRF for randomness, NFT character system, and Unity WebGL frontend.",
    status: "Live",
    featured: false,
    category: ["DApps & GameFi"],
    stack: ["Unity WebGL", "Solidity", "Photon PUN", "Chainlink VRF"],
    image: "/projects/teenpatti.jpg",
    url: "#",
  },
  {
    id: "memeverse",
    name: "MEMEVerse",
    description: "One-click meme coin launchpad with anti-rug protection and viral ranking.",
    longDescription: "Token launchpad with liquidity locking, anti-rug mechanisms, and social scoring algorithms.",
    status: "Live",
    featured: false,
    category: ["Launchpads & GameFi"],
    stack: ["Hardhat", "Solidity", "MongoDB", "Express", "React", "Node.js"],
    image: "/projects/memeverse.jpg",
    url: "#",
  },
  {
    id: "yes-cargo",
    name: "Yes Cargo",
    description: "Comprehensive cargo and logistics platform providing door-to-door shipping services in Saudi Arabia.",
    longDescription: "Full logistics management system with shipment tracking, driver management, and customer portal.",
    status: "Live",
    featured: false,
    category: ["Logistics & Supply Chain"],
    stack: ["Laravel", "PHP 8", "MySQL", "Bootstrap 5", "Vue.js"],
    image: "/projects/yes-cargo.jpg",
    url: "#",
  },
  {
    id: "tms",
    name: "TMS — Eleventh Hour Logistics",
    description: "Enterprise transport management system with real-time tracking and logistics operations dashboard.",
    longDescription: "Full-stack TMS with live GPS tracking, route optimization, driver scoring, and BI dashboards.",
    status: "Production",
    featured: false,
    category: ["Logistics & Supply Chain"],
    stack: ["Laravel", "Vue 3", "MySQL", "Redis", "WebSocket"],
    image: "/projects/tms.jpg",
    url: "#",
  },
];

// ─── SMART CONTRACTS ─────────────────────────────────────────
export const CONTRACTS = [
  {
    category: "Invoice & Payment",
    items: [
      {
        name: "Invoice Contract",
        network: "Sepolia",
        networkColor: "indigo",
        description: "Smart contract for invoice management and payment processing",
        address: "0x5fdc...4745",
        url: "https://sepolia.etherscan.io/address/0x5fdc94ff32f8a486dc55283043338c6242374745#code",
      },
    ],
  },
  {
    category: "RWA (Real World Assets)",
    items: [
      {
        name: "Upgradeable RWA Auction",
        network: "Sepolia",
        networkColor: "indigo",
        description: "Auction system for tokenized real-world assets",
        address: "0x3e22...f252",
        url: "https://sepolia.etherscan.io/address/0x3e2223ee75917bab6cca212aacd60fc8392af252#code",
      },
      {
        name: "Upgradeable RWA Escrow",
        network: "Sepolia",
        networkColor: "indigo",
        description: "Secure escrow for RWA transactions",
        address: "0x0265...76ec",
        url: "https://sepolia.etherscan.io/address/0x0265f1ab58feaf2082204e8bd53c448fa6ad76ec#code",
      },
      {
        name: "Upgradeable RWA Sale",
        network: "Sepolia",
        networkColor: "indigo",
        description: "Direct sale platform for real-world assets",
        address: "0xab29...de61",
        url: "https://sepolia.etherscan.io/address/0xab2998d91a5157320870a47cdb73ecdfcd04de61#code",
      },
    ],
  },
  {
    category: "NFT & Marketplace",
    items: [
      {
        name: "Upgradeable NFT Marketplace",
        network: "Sepolia",
        networkColor: "indigo",
        description: "Full-featured NFT marketplace with upgradeability",
        address: "0xa95c...5efe",
        url: "https://sepolia.etherscan.io/address/0xa95c517169751a434d5c3b6111404e0c18775efe#code",
      },
      {
        name: "1-to-1 Escrow",
        network: "Sepolia",
        networkColor: "indigo",
        description: "Peer-to-peer escrow for secure transactions",
        address: "0xdfe9...8f73",
        url: "https://sepolia.etherscan.io/address/0xdfe9379f507ae616fcc71d7227ccac6893828f73#code",
      },
    ],
  },
  {
    category: "Multi-Chain Production",
    items: [
      {
        name: "ERC-20 Token",
        network: "Ethereum Mainnet",
        networkColor: "violet",
        description: "ERC-20 token deployed on Ethereum mainnet",
        address: "0x7236...72d6",
        url: "https://etherscan.io/token/0x72362564c801161d0e5dcd74cce0ed83915672d6",
      },
      {
        name: "Polygon Contract",
        network: "Polygon",
        networkColor: "violet",
        description: "Smart contract on Polygon network",
        address: "0x89ec...d8fe",
        url: "https://polygonscan.com/address/0x89ecf29ff6bb0dfdb3f537b6be0d9ed782c1d8fe#code",
      },
      {
        name: "BSC Mainnet",
        network: "BNB Chain",
        networkColor: "gold",
        description: "Production contract on Binance Smart Chain",
        address: "0xa2bf...e28e",
        url: "https://bscscan.com/address/0xa2bf5bc642e342884aacf9b81e232bbcef96e28e",
      },
    ],
  },
];

// ─── EXPERIENCE ───────────────────────────────────────────────
export const EXPERIENCE = [
  {
    id: "fann",
    role: "Chief Technology Officer",
    company: "FANN",
    period: "Aug 2024 – Present",
    location: "Doha, Qatar · On-site",
    type: "Full-time",
    current: true,
    description:
      "Leading the development of an ArtTech ecosystem that redefines how physical and digital art are authenticated, valued, and traded.",
    achievements: [
      "Leading technical strategy for RWA & ArtTech fractional ownership platform",
      "Architected comprehensive blockchain infrastructure for art authentication and valuation",
      "Developed AI-powered valuation systems for digital and physical art assets",
    ],
    skills: ["Technology Management", "Blockchain Architecture", "AI/ML", "Solidity", "Web3"],
  },
  {
    id: "nftyart",
    role: "Blockchain Developer",
    company: "NFTyART",
    period: "Dec 2023 – Aug 2024",
    location: "Kuwait · Hybrid",
    type: "Full-time",
    current: false,
    description:
      "Served as Blockchain Technical Lead and Projects Manager, managing the development of blockchain smart contracts and Web3 platform infrastructure.",
    achievements: [
      "Led blockchain smart contract development and Web3 integrations",
      "Managed cross-functional development teams and project timelines",
      "Implemented secure smart contract architecture for NFT marketplace",
    ],
    skills: ["Project Management", "Blockchain", "Smart Contracts", "Solidity", "Web3", "NFTs"],
  },
  {
    id: "12sol",
    role: "Blockchain Developer",
    company: "12SOL",
    period: "Feb 2023 – Dec 2023",
    location: "Islamabad, Pakistan · Hybrid",
    type: "Full-time",
    current: false,
    description:
      "At 12SOL, a fast-moving startup blending blockchain with digital innovation, developed and audited Solidity smart contracts and implemented Web3 integrations.",
    achievements: [
      "Developed and audited Solidity smart contracts for asset transfers and escrow",
      "Implemented Web3.js integrations connecting smart contracts to frontend interfaces",
      "Collaborated across multi-disciplinary teams to create integrated blockchain products",
    ],
    skills: ["Solidity", "Smart Contracts", "Web3.js", "Ethereum", "DApp Development"],
  },
  {
    id: "freelance",
    role: "Freelance Developer",
    company: "Fiverr & Upwork",
    period: "Dec 2020 – Jan 2024",
    location: "Remote · Self-employed",
    type: "Freelance",
    current: false,
    description:
      "Built the foundation: 100+ projects across web development, blockchain, and smart contracts. 98% positive feedback rating. The chapter that shaped everything.",
    achievements: [
      "Successfully completed 100+ projects across web development, blockchain, and smart contracts",
      "Built strong client relationships with 98% positive feedback rating",
      "Specialized in full-stack development and blockchain solutions",
    ],
    skills: ["Solidity", "Smart Contracts", "JavaScript", "React", "Node.js", "Python", "Full-Stack"],
  },
  {
    id: "bratssoft",
    role: "Internship Trainee",
    company: "BratsSoft Solution",
    period: "Nov 2021 – Jan 2023",
    location: "Lahore, Pakistan · On-site",
    type: "Internship",
    current: false,
    description:
      "Explored Node.js and blockchain smart contracts in a professional team environment.",
    achievements: [
      "Gained foundational experience in Node.js and server-side development",
      "Explored blockchain technology and smart contract development",
    ],
    skills: ["Solidity", "Blockchain", "Node.js", "JavaScript"],
  },
  {
    id: "mca",
    role: "Engineer Intern",
    company: "MCA Education System",
    period: "Dec 2018 – Dec 2019",
    location: "Peshawar, Pakistan · On-site",
    type: "Internship",
    current: false,
    description: "Installed, configured, and maintained IT infrastructure including servers and network systems.",
    achievements: [
      "Installed and configured computers and network infrastructure",
      "Maintained file servers and Ethernet network systems",
    ],
    skills: ["IT Operations", "Networking", "HTML", "CSS", "PHP"],
  },
];

// ─── SKILLS ───────────────────────────────────────────────────
export const SKILL_GROUPS = [
  {
    category: "Blockchain & Web3",
    color: "gold",
    proficiency: 98,
    skills: ["Solidity", "TypeScript", "Hardhat", "Truffle", "Ethers.js", "Web3.js", "OpenZeppelin", "ERC Standards"],
  },
  {
    category: "DeFi & DApp Development",
    color: "teal",
    proficiency: 95,
    skills: ["React", "Next.js", "Solidity", "Web3.js", "Ethers.js", "DeFi Protocols", "Smart Contracts"],
  },
  {
    category: "Full-Stack (MERN)",
    color: "indigo",
    proficiency: 95,
    skills: ["JavaScript", "TypeScript", "React", "Next.js 14/15", "Express", "Node.js", "Redux/RTK", "Tailwind CSS"],
  },
  {
    category: "Backend & APIs",
    color: "violet",
    proficiency: 90,
    skills: ["Node.js", "Express.js", "RESTful APIs", "GraphQL", "PostgreSQL", "MongoDB", "Redis"],
  },
  {
    category: "AI & Machine Learning",
    color: "emerald",
    proficiency: 75,
    skills: ["Python", "TensorFlow", "Computer Vision", "AI/ML Integration", "Data Analytics"],
  },
  {
    category: "Infrastructure & DevOps",
    color: "teal",
    proficiency: 80,
    skills: ["IPFS", "Docker", "Vercel", "Netlify", "Git", "GitHub Actions", "Linux"],
  },
];

// ─── ARTICLES ─────────────────────────────────────────────────
export const ARTICLES = [
  {
    id: "nftyart-to-fann",
    title: "NFTyART to FANN: Building a Hybrid NFT Marketplace for Digital & Physical Art",
    excerpt:
      "From NFTyART's niche digital marketplace to FANN's revolutionary hybrid platform bridging physical artwork with NFTs. A comprehensive look at building scalable Web3 infrastructure.",
    date: "June 3, 2025",
    readTime: "18 min read",
    tags: ["NFT", "Blockchain", "Marketplace", "Web3"],
    url: "https://medium.com/@sabilkhattak77/nftyart-to-fann-building-a-hybrid-nft-marketplace-for-digital-physical-art-d538b8310152",
    featured: true,
  },
  {
    id: "future-of-art",
    title: "The Future of Art: Powered by Blockchain and Emerging Technologies",
    excerpt:
      "Art is transforming through intelligent code, augmented reality, and cryptographic signatures. Exploring the next decade of creative economies.",
    date: "May 19, 2025",
    readTime: "5 min read",
    tags: ["Blockchain", "Art", "Technology"],
    url: "https://medium.com/@sabilkhattak77/the-future-of-art-powered-by-blockchain-and-emerging-technologies-95a15222b541",
    featured: false,
  },
  {
    id: "beyond-crypto",
    title: "Beyond Crypto — How Blockchain is Revolutionizing Industries",
    excerpt:
      "Blockchain isn't just disrupting finance — it's quietly rewriting the rules of healthcare, supply chain, and everyday life.",
    date: "December 15, 2024",
    readTime: "8 min read",
    tags: ["Blockchain", "Healthcare", "Supply Chain", "Innovation"],
    url: "https://www.linkedin.com/pulse/edition-03-beyond-crypto-how-blockchain-industries-you-sabil-ahmad-z0wqf/",
    featured: false,
  },
  {
    id: "web3-architecture",
    title: "Building Resilient Web3 Architecture: Lessons from the Field",
    excerpt:
      "Technical insights from building production-ready DApps. Best practices for smart contract security, scalability, and developer velocity.",
    date: "November 20, 2024",
    readTime: "12 min read",
    tags: ["Web3", "Smart Contracts", "Architecture"],
    url: "https://www.linkedin.com/newsletters/7242043917003616256/",
    featured: false,
  },
];

// ─── ABOUT PILLARS ────────────────────────────────────────────
export const PILLARS = [
  {
    icon: "🔐",
    title: "Security & Auditability",
    description: "Smart contracts that audit clean — formal verification, comprehensive testing, zero shortcuts.",
  },
  {
    icon: "⚡",
    title: "Scalability",
    description: "High-performance architectures designed for millions of users and transactions from day one.",
  },
  {
    icon: "🔗",
    title: "Token Standards Mastery",
    description: "Expert implementation of ERC-20, 721, 1155, 4626, and complex tokenization scenarios.",
  },
  {
    icon: "📊",
    title: "Data-Driven Design",
    description: "Analytics-first architecture enabling real-time insights, not post-hoc reporting.",
  },
  {
    icon: "🚀",
    title: "Developer Velocity",
    description: "Modern tooling and practices that make teams fast, reliable, and impossible to slow down.",
  },
];

// ─── PROJECT CATEGORIES ───────────────────────────────────────
export const PROJECT_CATEGORIES = [
  "All",
  "DeFi & Tokenisation",
  "NFT Marketplaces",
  "DApps & GameFi",
  "Blockchain & Web3",
  "Launchpads & GameFi",
  "Logistics & Supply Chain",
];
