// ─────────────────────────────────────────────────────────────
// SABIL AHMAD PORTFOLIO — ALL CONTENT & DATA
// ─────────────────────────────────────────────────────────────

export const SITE = {
  name: "Sabil Ahmad",
  title: "CTO & Blockchain Engineer",
  tagline: "Building the Infrastructure of Tomorrow.",
  subTagline: "Blockchain architect. AI product engineer. Venture founder.",
  description:
    "CTO at FANN & Co-Founder at VentraM Group. Blockchain architect, AI product engineer, and venture founder. 60+ shipped products, 70+ smart contracts across 5 chains, 5 live startups. Based in Doha, Qatar.",
  url: "https://sabilahmad.com",
  email: "Info@sabilahmad.com",
  whatsapp: "97450389351",
  location: "Doha, Qatar",
  locationFull: "Doha, Qatar · Open to remote globally",
  availability: true,
  github: "https://github.com/sabilahmad77",
  linkedin: "https://linkedin.com/in/sabilahmad",
  twitter: "https://x.com/SabilAhmad77",
  telegram: "https://t.me/sabilahmad77",
  medium: "https://medium.com/@sabilkhattak77",
  currentRole: "Chief Technology Officer · FANN",
  currentLocation: "Doha, Qatar",
};

export const STATS = [
  { value: "60+", label: "Projects Delivered" },
  { value: "70+", label: "Smart Contracts" },
  { value: "5+",  label: "Startups Launched" },
  { value: "5+",  label: "Chains Deployed" },
];

// ─── VENTURES (My Startups) ──────────────────────────────────
export const VENTURES_FEATURED = [
  {
    id: "fann",
    name: "FANN",
    tagline: "The Verified Art Marketplace",
    status: "Live",
    statusColor: "emerald" as const,
    category: "Art Tech · Blockchain · AI/ML",
    logo: "/logos/fann.svg",
    url: "https://fann.art",
    tryfann: "https://tryfann.com",
    role: "Chief Technology Officer",
    period: "Aug 2024 – Present",
    location: "Doha, Qatar",
    description:
      "Art is a multi-trillion-dollar asset class with a provenance problem. FANN solves it: blockchain-verified ownership records, AI-powered valuation, and AR previews — all native to the GCC market. I architect the entire technical foundation.",
    shortDescription:
      "Blockchain-native art marketplace redefining how physical art is owned, verified, and traded in the GCC.",
    achievements: [
      "Leading technical strategy for RWA & ArtTech fractional ownership platform",
      "Architected comprehensive blockchain infrastructure for art authentication",
      "Developed AI-powered valuation systems for digital and physical art assets",
      "Built AR preview system for physical art works",
    ],
    stack: ["React", "Node.js", "Solidity", "IPFS", "AI/ML", "Web3"],
    highlight: true,
  },
  {
    id: "principal-desk",
    name: "Principal Desk",
    tagline: "School Management, Reimagined",
    status: "Live",
    statusColor: "emerald" as const,
    category: "EdTech · SaaS",
    logo: "/logos/principal-desk.svg",
    url: "https://principaldesk.com",
    role: "Founder & CTO",
    period: "Founded",
    location: "GCC / MENA",
    description:
      "Educational institutions run on spreadsheets and group chats. Principal Desk replaces both — unified parent communication, academic tracking, and administration in one platform built for the MENA region.",
    shortDescription:
      "Comprehensive school management platform for educational institutions with integrated communication tools.",
    achievements: [
      "Real-time parent-teacher messaging system",
      "Automated grade reporting and academic tracking",
      "Multi-school SaaS architecture",
      "Integrated payment and scheduling systems",
    ],
    stack: ["React", "Node.js", "PostgreSQL", "Socket.io", "Redis"],
    highlight: true,
  },
];

export const VENTURES_MINI = [
  {
    id: "blockchain-explorer",
    name: "Blockchain Explorer",
    status: "Live",
    url: "https://blockchainexplorer.info",
    description: "Advanced multi-chain blockchain explorer with real-time analytics and smart contract analysis.",
    stack: ["React", "Node.js", "GraphQL", "Web3.js"],
    category: "Developer Tools",
  },
  {
    id: "scan-halal-ai",
    name: "Scan Halal AI",
    status: "Live",
    url: "https://scanhalalai.com/",
    description: "AI-powered halal food verification app using computer vision and Islamic jurisprudence.",
    stack: ["React Native", "Python", "TensorFlow", "Computer Vision"],
    category: "Food Tech · Islamic Tech",
  },
  {
    id: "salesicon",
    name: "Salesicon",
    status: "Live",
    url: "https://salesicon.store",
    description: "AI-powered sales intelligence platform providing real-time insights and automation for sales teams.",
    stack: ["React", "Python", "TensorFlow", "PostgreSQL"],
    category: "SaaS · Sales Tech",
  },
  {
    id: "socicart",
    name: "SociCart",
    status: "Soon",
    url: "#",
    description: "Social commerce platform that transforms shopping into a collaborative and interactive experience.",
    stack: ["React", "Node.js", "MongoDB", "Socket.io"],
    category: "E-commerce · Social",
  },
];

// ─── FEATURED PROJECTS (Client Work) ────────────────────────
export const PROJECTS = [
  {
    id: "viko",
    name: "VIKO",
    description: "Blockchain-based digital platform for token infrastructure and market intelligence, supporting crypto ecosystems with analytics, launch mechanisms, and trend insights.",
    longDescription: "Full-stack blockchain platform with token launch infrastructure, real-time market analytics, and trend-based token intelligence for crypto ecosystems.",
    status: "Live",
    featured: true,
    category: ["Blockchain & Web3", "DeFi & Tokenisation"],
    stack: ["React", "Node.js", "Solidity", "Web3.js", "Blockchain Analytics", "TypeScript"],
    image: "/projects/viko.jpg",
    url: "#",
  },
  {
    id: "mexc-crypto",
    name: "MEXC Crypto",
    description: "Advanced cryptocurrency trading platform with professional-grade tools and gold mining investment operations.",
    longDescription: "Full-featured cryptocurrency trading platform with real-time WebSocket price feeds, portfolio analytics, and DeFi integrations.",
    status: "Live",
    featured: true,
    category: ["DeFi & Tokenisation", "Fintech"],
    stack: ["React", "Node.js", "WebSocket", "MongoDB", "Redis", "Web3.js"],
    image: "/projects/mexc.jpg",
    url: "#",
  },
  {
    id: "nftyart",
    name: "NFTyART",
    description: "NFT marketplace platform for digital art creation, trading, and community building with full Web3 integration.",
    longDescription: "Production-grade NFT marketplace with IPFS storage, smart contract minting, and community governance.",
    status: "Live",
    featured: true,
    category: ["Blockchain & Web3", "Marketplace"],
    stack: ["React", "Solidity", "IPFS", "Web3.js", "Node.js", "MongoDB"],
    image: "/projects/nftyart2.jpg",
    url: "#",
  },
  {
    id: "tryfann",
    name: "TryFANN",
    description: "Blockchain-native ArtTech platform connecting artists, collectors, and galleries through tokenized ownership on Arbitrum.",
    longDescription: "Built as CTO of FANN — a Web3 art marketplace enabling digital and physical art tokenization, NFT minting, auction mechanics, and collector communities on Arbitrum One.",
    status: "Live",
    featured: true,
    category: ["Blockchain & Web3", "Marketplace"],
    stack: ["Next.js", "React", "Solidity", "IPFS", "Arbitrum", "Node.js", "The Graph"],
    image: "/projects/tryfann.jpg",
    url: "https://fann.art",
  },
  {
    id: "bitxgold",
    name: "BITXGOLD",
    description: "Gold-backed token ecosystem with 1:1 bullion tokenization and full DeFi integration.",
    longDescription: "RWA tokenization platform for gold assets, with on-chain proof of reserves and yield-bearing vaults.",
    status: "Live",
    featured: true,
    category: ["DeFi & Tokenisation"],
    stack: ["MongoDB", "Express", "React", "Node.js", "Solidity", "Hardhat", "Chainlink"],
    image: "/projects/bitxgold.jpg",
    url: "#",
  },
  {
    id: "gold-smart-chain",
    name: "Gold Smart Chain",
    description: "Private permissioned blockchain for compliant gold tokenization with L2 bridges.",
    longDescription: "Enterprise-grade permissioned chain built on Geth with custom consensus, L2 bridge infrastructure, and compliance modules.",
    status: "Production",
    featured: true,
    category: ["DeFi & Tokenisation"],
    stack: ["MongoDB", "Express", "React", "Node.js", "Geth", "Solidity"],
    image: "/projects/gold-smart-chain.jpg",
    url: "#",
  },
  {
    id: "leet-swap",
    name: "LEET Swap",
    description: "Gas-optimized DEX with pro-mode charting and gamer-centric LP incentives.",
    longDescription: "Uniswap v3 fork with custom fee tiers, gamified liquidity mining, and integrated TradingView charts.",
    status: "Live",
    featured: true,
    category: ["DeFi & Tokenisation"],
    stack: ["React", "Solidity", "Uniswap v3 SDK", "The Graph", "Ethers.js"],
    image: "/projects/leet-swap.jpg",
    url: "#",
  },
  {
    id: "allocate",
    name: "Allocate",
    description: "Decentralized crowdfunding platform with milestone-based fund release and DAO governance.",
    longDescription: "Web3 crowdfunding protocol with escrow-gated milestones, multi-sig governance, and on-chain reporting.",
    status: "Live",
    featured: false,
    category: ["DeFi & Tokenisation"],
    stack: ["MongoDB", "Express", "React", "Node.js", "Solidity", "OpenZeppelin"],
    image: "/projects/allocate.jpg",
    url: "#",
  },
  {
    id: "babyloan",
    name: "BABYloan",
    description: "Mobile-first micro-lending platform for crypto-collateralized stablecoin loans.",
    longDescription: "DeFi lending protocol with automated liquidation, risk scoring, and mobile-optimized UX.",
    status: "Beta",
    featured: false,
    category: ["DeFi & Tokenisation"],
    stack: ["MongoDB", "Express", "React", "Node.js", "Solidity", "Chainlink"],
    image: "/projects/babyloan.jpg",
    url: "#",
  },
  {
    id: "cex-arbitrage",
    name: "CEX Arbitrage",
    description: "Low-latency arbitrage bot monitoring price spreads across major centralized exchanges.",
    longDescription: "High-frequency trading bot with sub-50ms order execution, multi-exchange API management, and risk controls.",
    status: "Live",
    featured: false,
    category: ["DeFi & Tokenisation"],
    stack: ["Node.js", "TypeScript", "CCXT", "Redis", "WebSocket"],
    image: "/projects/cex-arb.jpg",
    url: "#",
  },
  {
    id: "midnight-trades",
    name: "MidNightTrades",
    description: "Dark-themed NFT marketplace for nightclub-inspired art with real-time bidding.",
    longDescription: "Niche NFT marketplace with live auction engine, artist royalty enforcement, and curated drops.",
    status: "Live",
    featured: false,
    category: ["NFT Marketplaces"],
    stack: ["MongoDB", "Express", "React", "Node.js", "Solidity", "Socket.io"],
    image: "/projects/midnight.jpg",
    url: "#",
  },
  {
    id: "bleney",
    name: "Bleney NFT Marketplace",
    description: "Generative art NFT hub with lazy minting and fractional ownership vaults.",
    longDescription: "Next.js-powered NFT platform with gasless minting via EIP-2771, The Graph indexing, and fractional vault contracts.",
    status: "Live",
    featured: false,
    category: ["NFT Marketplaces"],
    stack: ["Next.js", "Solidity", "The Graph", "IPFS", "Ethers.js"],
    image: "/projects/bleney.jpg",
    url: "#",
  },
  {
    id: "riseabove",
    name: "RISEABOVE",
    description: "DAO-powered creator toolkit with AR preview and tokenized community governance.",
    longDescription: "NFT platform with Snapshot.org governance integration, on-chain voting, and experimental AR artwork preview.",
    status: "Live",
    featured: false,
    category: ["NFT Marketplaces"],
    stack: ["Next.js", "Solidity", "IPFS", "Snapshot.org", "Ethers.js"],
    image: "/projects/riseabove.jpg",
    url: "#",
  },
  {
    id: "solana-dapp",
    name: "Solana DApp",
    description: "High-APY yield farming protocol with auto-compounding vaults on Solana.",
    longDescription: "Anchor-based DeFi protocol on Solana with automated compound strategies and liquidity mining.",
    status: "Live",
    featured: false,
    category: ["DApps & GameFi"],
    stack: ["React", "Anchor", "Rust", "Solana Web3.js", "TypeScript"],
    image: "/projects/solana.jpg",
    url: "#",
  },
  {
    id: "teen-patti",
    name: "TeenPatti DApp",
    description: "Blockchain-based card game with provably fair randomness and NFT integration.",
    longDescription: "Fully on-chain card game with Chainlink VRF for randomness, NFT character system, and Unity WebGL frontend.",
    status: "Live",
    featured: false,
    category: ["DApps & GameFi"],
    stack: ["Unity WebGL", "Solidity", "Photon PUN", "Chainlink VRF"],
    image: "/projects/teenpatti.jpg",
    url: "#",
  },
  {
    id: "memeverse",
    name: "MEMEVerse",
    description: "One-click meme coin launchpad with anti-rug protection and viral ranking.",
    longDescription: "Token launchpad with liquidity locking, anti-rug mechanisms, and social scoring algorithms.",
    status: "Live",
    featured: false,
    category: ["Launchpads & GameFi"],
    stack: ["Hardhat", "Solidity", "MongoDB", "Express", "React", "Node.js"],
    image: "/projects/memeverse.jpg",
    url: "#",
  },
  {
    id: "yes-cargo",
    name: "Yes Cargo",
    description: "Comprehensive cargo and logistics platform providing door-to-door shipping services in Saudi Arabia.",
    longDescription: "Full logistics management system with shipment tracking, driver management, and customer portal.",
    status: "Live",
    featured: false,
    category: ["Logistics & Supply Chain"],
    stack: ["Laravel", "PHP 8", "MySQL", "Bootstrap 5", "Vue.js"],
    image: "/projects/yes-cargo.jpg",
    url: "#",
  },
  {
    id: "tms",
    name: "TMS — Eleventh Hour Logistics",
    description: "Enterprise transport management system with real-time tracking and logistics operations dashboard.",
    longDescription: "Full-stack TMS with live GPS tracking, route optimization, driver scoring, and BI dashboards.",
    status: "Production",
    featured: false,
    category: ["Logistics & Supply Chain"],
    stack: ["Laravel", "Vue 3", "MySQL", "Redis", "WebSocket"],
    image: "/projects/tms.jpg",
    url: "#",
  },
];

// ─── SMART CONTRACTS (inline preview for Projects section) ────
export const CONTRACTS = [
  {
    category: "FANN ArtTech — Arbitrum One",
    items: [
      {
        name: "RWA Token Factory",
        network: "Arbitrum One",
        networkColor: "indigo",
        description: "ERC-3643 compliant factory for deploying tokenized real-world art assets with KYC gating.",
        address: "0x1a05...EE99",
        url: "https://arbiscan.io/address/0x1a0533ee2e6C4a08eA17ae0CB61Bf68D1CE3EE99",
      },
      {
        name: "Sale Marketplace",
        network: "Arbitrum One",
        networkColor: "indigo",
        description: "Fixed-price marketplace for compliant RWA token sales with fee distribution.",
        address: "0x0556...91Df",
        url: "https://arbiscan.io/address/0x055666C504baaFf95e0eC665BEf47494E3B591Df",
      },
      {
        name: "Auction Marketplace",
        network: "Arbitrum One",
        networkColor: "indigo",
        description: "On-chain auction system for tokenized art assets with bidding and settlement.",
        address: "0x39E5...89f7",
        url: "https://arbiscan.io/address/0x39E5a1C6025771b47fdA464F06285EB7cebC89f7",
      },
      {
        name: "Identity Registry",
        network: "Arbitrum One",
        networkColor: "indigo",
        description: "On-chain identity management for ERC-3643 compliance — maps wallet to verified DID.",
        address: "0xCBA2...95c0",
        url: "https://arbiscan.io/address/0xCBA2f2d50F9bADB18d726cc685E32213967795c0",
      },
    ],
  },
  {
    category: "NFT & Marketplace",
    items: [
      {
        name: "NFTyART Marketplace",
        network: "BNB Chain",
        networkColor: "gold",
        description: "Full-stack NFT marketplace with minting, trading, royalties, and on-chain governance.",
        address: "0x280A...d859",
        url: "https://bscscan.com/address/0x280A0B919D802A7d0bDD8222fcBb8d1E4d9Ad859#readContract",
      },
      {
        name: "NFT Collection Contract",
        network: "BNB Chain",
        networkColor: "gold",
        description: "ERC-721 NFT collection with metadata, royalty enforcement, and lazy minting.",
        address: "0xf342...5232",
        url: "https://bscscan.com/address/0xf3422b8e8ea2cd3bbf13aea82786683085f35232",
      },
    ],
  },
  {
    category: "DeFi & Multi-chain",
    items: [
      {
        name: "DEX Liquidity Pair",
        network: "BNB Chain",
        networkColor: "gold",
        description: "Automated market maker liquidity pool contract on BSC with swap and LP functionality.",
        address: "0xc062...6894",
        url: "https://dexscreener.com/bsc/0xc0621b07B765F4118C5221e7984FE3F383fc6894",
      },
      {
        name: "ERC-20 Token",
        network: "Ethereum Mainnet",
        networkColor: "violet",
        description: "Production ERC-20 token deployed on Ethereum mainnet with transfer and approval mechanics.",
        address: "0x7236...72d6",
        url: "https://etherscan.io/token/0x72362564c801161d0e5dcd74cce0ed83915672d6",
      },
      {
        name: "Polygon DApp Contract",
        network: "Polygon",
        networkColor: "violet",
        description: "Smart contract on Polygon PoS with gas-optimised logic for high-throughput operations.",
        address: "0x89ec...d8fe",
        url: "https://polygonscan.com/address/0x89ecf29ff6bb0dfdb3f537b6be0d9ed782c1d8fe#code",
      },
    ],
  },
];

// ─── COMPREHENSIVE SMART CONTRACT PORTFOLIO ───────────────────
export const SMART_CONTRACTS: {
  id: string;
  name: string;
  project: string;
  category: string;
  network: string;
  networkColor: string;
  chain: string;
  type: string;
  description: string;
  address: string;
  shortAddress: string;
  url: string;
  featured: boolean;
  status: "Production" | "Testnet";
  date?: string;
}[] = [
  // ── FANN ArtTech — Arbitrum One (Production) ──────────────
  {
    id: "fann-arb-rwa-factory",
    name: "RWA Token Factory",
    project: "FANN ArtTech",
    category: "RWA Infrastructure",
    network: "Arbitrum One",
    networkColor: "#6B7FE8",
    chain: "Arbitrum",
    type: "ERC-3643 Factory",
    description: "Factory contract for minting ERC-3643 compliant real-world asset tokens. Handles token deployment with built-in identity verification, KYC gating, and modular compliance enforcement.",
    address: "0x1a0533ee2e6C4a08eA17ae0CB61Bf68D1CE3EE99",
    shortAddress: "0x1a05...EE99",
    url: "https://arbiscan.io/address/0x1a0533ee2e6C4a08eA17ae0CB61Bf68D1CE3EE99",
    featured: true,
    status: "Production",
    date: "Feb 2025",
  },
  {
    id: "fann-arb-sale-marketplace",
    name: "Sale Marketplace",
    project: "FANN ArtTech",
    category: "RWA Infrastructure",
    network: "Arbitrum One",
    networkColor: "#6B7FE8",
    chain: "Arbitrum",
    type: "Marketplace Contract",
    description: "Fixed-price marketplace for tokenized real-world art assets. Handles listing, purchasing, platform fee distribution, and ERC-3643 compliant ownership transfer.",
    address: "0x055666C504baaFf95e0eC665BEf47494E3B591Df",
    shortAddress: "0x0556...91Df",
    url: "https://arbiscan.io/address/0x055666C504baaFf95e0eC665BEf47494E3B591Df",
    featured: true,
    status: "Production",
    date: "Feb 2025",
  },
  {
    id: "fann-arb-auction-marketplace",
    name: "Auction Marketplace",
    project: "FANN ArtTech",
    category: "RWA Infrastructure",
    network: "Arbitrum One",
    networkColor: "#6B7FE8",
    chain: "Arbitrum",
    type: "Auction Contract",
    description: "On-chain English auction system for tokenized art assets. Supports timed bidding, reserve prices, automatic settlement, and royalty payments.",
    address: "0x39E5a1C6025771b47fdA464F06285EB7cebC89f7",
    shortAddress: "0x39E5...89f7",
    url: "https://arbiscan.io/address/0x39E5a1C6025771b47fdA464F06285EB7cebC89f7",
    featured: true,
    status: "Production",
    date: "Feb 2025",
  },
  {
    id: "fann-arb-identity-registry",
    name: "Identity Registry",
    project: "FANN ArtTech",
    category: "Compliance & KYC",
    network: "Arbitrum One",
    networkColor: "#6B7FE8",
    chain: "Arbitrum",
    type: "Identity Registry (ERC-3643)",
    description: "On-chain identity management mapping wallet addresses to verified DID claims. Core compliance layer for the FANN ArtTech ERC-3643 token ecosystem.",
    address: "0xCBA2f2d50F9bADB18d726cc685E32213967795c0",
    shortAddress: "0xCBA2...95c0",
    url: "https://arbiscan.io/address/0xCBA2f2d50F9bADB18d726cc685E32213967795c0",
    featured: true,
    status: "Production",
    date: "Feb 2025",
  },
  {
    id: "fann-arb-kyc-registry",
    name: "KYC Registry",
    project: "FANN ArtTech",
    category: "Compliance & KYC",
    network: "Arbitrum One",
    networkColor: "#6B7FE8",
    chain: "Arbitrum",
    type: "KYC Module",
    description: "Modular KYC verification contract storing claim hashes for verified investors. Integrates with IdentityRegistry to gate token transfers to compliant wallets only.",
    address: "0x27E039FD5343c842eee7E848b92C35D3AA05fAc9",
    shortAddress: "0x27E0...fAc9",
    url: "https://arbiscan.io/address/0x27E039FD5343c842eee7E848b92C35D3AA05fAc9",
    featured: true,
    status: "Production",
    date: "Feb 2025",
  },
  {
    id: "fann-arb-modular-compliance",
    name: "Modular Compliance",
    project: "FANN ArtTech",
    category: "Compliance & KYC",
    network: "Arbitrum One",
    networkColor: "#6B7FE8",
    chain: "Arbitrum",
    type: "Compliance Engine",
    description: "Pluggable compliance rules engine enforcing transfer restrictions, holding limits, and jurisdictional rules across all FANN RWA token operations.",
    address: "0x784a466B6723c0F332Eb255C5762451aE8e28656",
    shortAddress: "0x784a...8656",
    url: "https://arbiscan.io/address/0x784a466B6723c0F332Eb255C5762451aE8e28656",
    featured: true,
    status: "Production",
    date: "Feb 2025",
  },
  {
    id: "fann-arb-sale-escrow",
    name: "Sale Escrow",
    project: "FANN ArtTech",
    category: "RWA Infrastructure",
    network: "Arbitrum One",
    networkColor: "#6B7FE8",
    chain: "Arbitrum",
    type: "Escrow Contract",
    description: "Trustless escrow for fixed-price RWA sales. Holds funds during transaction lifecycle and releases payment to seller on confirmed token delivery.",
    address: "0x748625E390e366fbe23412404070E7fDba07A141",
    shortAddress: "0x7486...7A141",
    url: "https://arbiscan.io/address/0x748625E390e366fbe23412404070E7fDba07A141",
    featured: true,
    status: "Production",
    date: "Feb 2025",
  },
  {
    id: "fann-arb-auction-escrow",
    name: "Auction Escrow",
    project: "FANN ArtTech",
    category: "RWA Infrastructure",
    network: "Arbitrum One",
    networkColor: "#6B7FE8",
    chain: "Arbitrum",
    type: "Escrow Contract",
    description: "Escrow contract for on-chain art auctions. Holds bidder funds throughout the auction lifecycle and executes atomic settlement at auction close.",
    address: "0x9dFA1b57456a82c086383EA0D660457Ad4e2c70B",
    shortAddress: "0x9dFA...c70B",
    url: "https://arbiscan.io/address/0x9dFA1b57456a82c086383EA0D660457Ad4e2c70B",
    featured: false,
    status: "Production",
    date: "Feb 2025",
  },

  // ── NFTyART — BNB Chain (Production) ────────────────────────
  {
    id: "nftyart-marketplace",
    name: "NFT Marketplace",
    project: "NFTyART",
    category: "NFT & Marketplace",
    network: "BNB Chain",
    networkColor: "#C9A655",
    chain: "BSC",
    type: "NFT Marketplace",
    description: "Full-stack NFT marketplace contract supporting minting, fixed-price sales, bidding, and royalty distribution. On-chain governance and community whitelisting.",
    address: "0x280A0B919D802A7d0bDD8222fcBb8d1E4d9Ad859",
    shortAddress: "0x280A...d859",
    url: "https://bscscan.com/address/0x280A0B919D802A7d0bDD8222fcBb8d1E4d9Ad859#readContract",
    featured: true,
    status: "Production",
    date: "2023",
  },
  {
    id: "nftyart-nft-collection",
    name: "NFT Collection Contract",
    project: "NFTyART",
    category: "NFT & Marketplace",
    network: "BNB Chain",
    networkColor: "#C9A655",
    chain: "BSC",
    type: "ERC-721 NFT",
    description: "ERC-721 NFT collection with on-chain metadata, creator royalty enforcement (EIP-2981), batch minting, and whitelist-gated presale phases.",
    address: "0xf3422b8e8ea2cd3bbf13aea82786683085f35232",
    shortAddress: "0xf342...5232",
    url: "https://bscscan.com/address/0xf3422b8e8ea2cd3bbf13aea82786683085f35232",
    featured: true,
    status: "Production",
    date: "2023",
  },
  {
    id: "nftyart-bsc-1",
    name: "NFTyART Contract #1",
    project: "NFTyART",
    category: "NFT & Marketplace",
    network: "BNB Chain",
    networkColor: "#C9A655",
    chain: "BSC",
    type: "BSC Deployment",
    description: "Smart contract deployed as part of the NFTyART ecosystem on BNB Chain mainnet. Handles platform-specific logic for digital art tokenisation.",
    address: "0xaa4ded8cf342f1eb6922594046958f4d42ff3877",
    shortAddress: "0xaa4d...3877",
    url: "https://bscscan.com/tx/0xaa4ded8cf342f1eb6922594046958f4d42ff387731afa3c3a7261f473fd5d9e5",
    featured: false,
    status: "Production",
    date: "2023",
  },
  {
    id: "nftyart-bsc-2",
    name: "NFTyART Contract #2",
    project: "NFTyART",
    category: "NFT & Marketplace",
    network: "BNB Chain",
    networkColor: "#C9A655",
    chain: "BSC",
    type: "BSC Deployment",
    description: "Secondary contract in the NFTyART BSC deployment suite. Manages platform treasury, fee collection, and artist reward distribution.",
    address: "0xf08333f5483186b2686df2f4eda59f62e3a25f60",
    shortAddress: "0xf083...5f60",
    url: "https://bscscan.com/tx/0xf08333f5483186b2686df2f4eda59f62e3a25f6011e4e5211f22ab4ec15bb090",
    featured: false,
    status: "Production",
    date: "2023",
  },
  {
    id: "nftyart-bsc-3",
    name: "NFTyART Contract #3",
    project: "NFTyART",
    category: "NFT & Marketplace",
    network: "BNB Chain",
    networkColor: "#C9A655",
    chain: "BSC",
    type: "BSC Deployment",
    description: "Third contract in the NFTyART suite handling staking, yield distribution, and governance token mechanics for platform participants.",
    address: "0xc81d25a1c9c4c652fe72c4d56e4eb98915801c39",
    shortAddress: "0xc81d...1c39",
    url: "https://bscscan.com/tx/0xc81d25a1c9c4c652fe72c4d56e4eb98915801c39536c4602594cd6021004735c",
    featured: false,
    status: "Production",
    date: "2023",
  },
  {
    id: "nftyart-bsc-4",
    name: "NFTyART Contract #4",
    project: "NFTyART",
    category: "NFT & Marketplace",
    network: "BNB Chain",
    networkColor: "#C9A655",
    chain: "BSC",
    type: "BSC Deployment",
    description: "Auction and bidding contract for the NFTyART marketplace. Supports English auctions with timed expirations and automatic highest-bid settlement.",
    address: "0x7eb1ea293958d7db0f27c4ec15f429baeb1c7c12",
    shortAddress: "0x7eb1...7c12",
    url: "https://bscscan.com/tx/0x7eb1ea293958d7db0f27c4ec15f429baeb1c7c12114a4fdbb9cfcac736d12ae6",
    featured: false,
    status: "Production",
    date: "2023",
  },
  {
    id: "nftyart-bsc-5",
    name: "NFTyART Contract #5",
    project: "NFTyART",
    category: "NFT & Marketplace",
    network: "BNB Chain",
    networkColor: "#C9A655",
    chain: "BSC",
    type: "BSC Deployment",
    description: "Royalty enforcement contract ensuring artist royalty payments on secondary sales across all NFTyART marketplace interactions.",
    address: "0x6994c0cb77e8cf4de145b917efc4bdf388cfb7c3",
    shortAddress: "0x6994...b7c3",
    url: "https://bscscan.com/tx/0x6994c0cb77e8cf4de145b917efc4bdf388cfb7c33d7084a267ec08b4f1622f1b",
    featured: false,
    status: "Production",
    date: "2023",
  },
  {
    id: "nftyart-bsc-6",
    name: "NFTyART Contract #6",
    project: "NFTyART",
    category: "NFT & Marketplace",
    network: "BNB Chain",
    networkColor: "#C9A655",
    chain: "BSC",
    type: "BSC Deployment",
    description: "Launchpad contract for curated NFT collection drops with whitelist phases, public mint pricing, and anti-bot protections.",
    address: "0x5bd0041814a054141822ad1a3b3d485f35d79a3e",
    shortAddress: "0x5bd0...9a3e",
    url: "https://bscscan.com/tx/0x5bd0041814a054141822ad1a3b3d485f35d79a3e492f76ca0b1480e2d9631c8c",
    featured: false,
    status: "Production",
    date: "2023",
  },
  {
    id: "nftyart-bsc-7",
    name: "NFTyART Contract #7",
    project: "NFTyART",
    category: "NFT & Marketplace",
    network: "BNB Chain",
    networkColor: "#C9A655",
    chain: "BSC",
    type: "BSC Deployment",
    description: "Escrow contract for peer-to-peer NFT trades, holding assets in a trustless vault until both parties confirm the exchange.",
    address: "0x1e9708f8c588e9f0ba34e59defd0df1de940af41",
    shortAddress: "0x1e97...af41",
    url: "https://bscscan.com/tx/0x1e9708f8c588e9f0ba34e59defd0df1de940af41af13f67b807ea135462b7c1e",
    featured: false,
    status: "Production",
    date: "2023",
  },
  {
    id: "nftyart-bsc-8",
    name: "NFTyART Contract #8",
    project: "NFTyART",
    category: "NFT & Marketplace",
    network: "BNB Chain",
    networkColor: "#C9A655",
    chain: "BSC",
    type: "BSC Deployment",
    description: "Batch-transfer utility contract enabling gasless multi-token transfers and bulk NFT operations for the NFTyART platform.",
    address: "0x6cf47695142bab37e07d3fe71b3c6eb920acebc8",
    shortAddress: "0x6cf4...ebc8",
    url: "https://bscscan.com/tx/0x6cf47695142bab37e07d3fe71b3c6eb920acebc862a9aaf344db627649a059fb",
    featured: false,
    status: "Production",
    date: "2023",
  },
  {
    id: "nftyart-bsc-9",
    name: "NFTyART Contract #9",
    project: "NFTyART",
    category: "NFT & Marketplace",
    network: "BNB Chain",
    networkColor: "#C9A655",
    chain: "BSC",
    type: "BSC Deployment",
    description: "Governance and DAO voting contract giving NFTyART token holders voting rights on platform upgrades, fee parameters, and treasury allocations.",
    address: "0xb53bd25ef11140be7737a0f7d1c3ecc6dc68fa5c",
    shortAddress: "0xb53b...fa5c",
    url: "https://bscscan.com/tx/0xb53bd25ef11140be7737a0f7d1c3ecc6dc68fa5cb8ecdd5c3fca2f944343c6c0",
    featured: false,
    status: "Production",
    date: "2023",
  },
  {
    id: "nftyart-bsc-10",
    name: "NFTyART Contract #10",
    project: "NFTyART",
    category: "NFT & Marketplace",
    network: "BNB Chain",
    networkColor: "#C9A655",
    chain: "BSC",
    type: "BSC Deployment",
    description: "Token vesting contract for team and investor token allocation with cliff periods and linear unlock schedules.",
    address: "0x12e5408edda613cff82309321ef584e0d1103a0d",
    shortAddress: "0x12e5...3a0d",
    url: "https://bscscan.com/tx/0x12e5408edda613cff82309321ef584e0d1103a0d13a214e5c62566dcedd24630",
    featured: false,
    status: "Production",
    date: "2023",
  },

  // ── DEX / DeFi — BNB Chain (Production) ────────────────────
  {
    id: "leet-swap-dex",
    name: "DEX Liquidity Pair",
    project: "LEET Swap",
    category: "DeFi & DEX",
    network: "BNB Chain",
    networkColor: "#C9A655",
    chain: "BSC",
    type: "AMM LP Pair",
    description: "Automated market maker liquidity pool on BNB Chain. Enables token swaps, LP deposits, and yield farming with custom fee tiers.",
    address: "0xc0621b07B765F4118C5221e7984FE3F383fc6894",
    shortAddress: "0xc062...6894",
    url: "https://dexscreener.com/bsc/0xc0621b07B765F4118C5221e7984FE3F383fc6894",
    featured: true,
    status: "Production",
    date: "2023",
  },
  {
    id: "bsc-production-main",
    name: "DeFi Production Contract",
    project: "Client Project",
    category: "DeFi & DEX",
    network: "BNB Chain",
    networkColor: "#C9A655",
    chain: "BSC",
    type: "DeFi Contract",
    description: "Production DeFi contract on BNB Chain mainnet for a client project. Handles staking, yield distribution, and token locking mechanisms.",
    address: "0xa2bf5bc642e342884aacf9b81e232bbcef96e28e",
    shortAddress: "0xa2bf...e28e",
    url: "https://bscscan.com/address/0xa2bf5bc642e342884aacf9b81e232bbcef96e28e",
    featured: false,
    status: "Production",
    date: "2022",
  },

  // ── Multi-chain Production ───────────────────────────────────
  {
    id: "eth-erc20-token",
    name: "ERC-20 Token (Mainnet)",
    project: "Client Project",
    category: "Token Contracts",
    network: "Ethereum Mainnet",
    networkColor: "#9375B5",
    chain: "Ethereum",
    type: "ERC-20 Token",
    description: "Production ERC-20 token on Ethereum mainnet with full transfer, approval, and allowance mechanics. Verified and audited for client deployment.",
    address: "0x72362564c801161d0e5dcd74cce0ed83915672d6",
    shortAddress: "0x7236...72d6",
    url: "https://etherscan.io/token/0x72362564c801161d0e5dcd74cce0ed83915672d6",
    featured: true,
    status: "Production",
    date: "2022",
  },
  {
    id: "polygon-dapp",
    name: "Polygon DApp Contract",
    project: "Client Project",
    category: "DeFi & DEX",
    network: "Polygon",
    networkColor: "#9375B5",
    chain: "Polygon",
    type: "DApp Contract",
    description: "Gas-optimised smart contract on Polygon PoS for a client DApp. Implements custom logic with low-cost transaction processing for high-frequency operations.",
    address: "0x89ecf29ff6bb0dfdb3f537b6be0d9ed782c1d8fe",
    shortAddress: "0x89ec...d8fe",
    url: "https://polygonscan.com/address/0x89ecf29ff6bb0dfdb3f537b6be0d9ed782c1d8fe#code",
    featured: false,
    status: "Production",
    date: "2022",
  },

  // ── FANN ArtTech — Sepolia Testnet ────────────────────────
  {
    id: "fann-sep-rwa-factory",
    name: "RWA Token Factory (Testnet)",
    project: "FANN ArtTech",
    category: "RWA Infrastructure",
    network: "Sepolia Testnet",
    networkColor: "#45E3D3",
    chain: "Sepolia",
    type: "ERC-3643 Factory",
    description: "Testnet deployment of the FANN RWA Token Factory for integration testing and staging validation before Arbitrum mainnet.",
    address: "0x72302b80d2BFF1DDF57c20a465aeff8409C9f4D0",
    shortAddress: "0x7230...f4D0",
    url: "https://sepolia.etherscan.io/address/0x72302b80d2BFF1DDF57c20a465aeff8409C9f4D0",
    featured: false,
    status: "Testnet",
    date: "2024",
  },
  {
    id: "fann-sep-sale-marketplace",
    name: "Sale Marketplace (Testnet)",
    project: "FANN ArtTech",
    category: "RWA Infrastructure",
    network: "Sepolia Testnet",
    networkColor: "#45E3D3",
    chain: "Sepolia",
    type: "Marketplace Contract",
    description: "Sepolia testnet version of the FANN fixed-price art marketplace for QA testing and investor demonstrations.",
    address: "0x37d298e6587412C36006566c9036d2cD9AA99960",
    shortAddress: "0x37d2...9960",
    url: "https://sepolia.etherscan.io/address/0x37d298e6587412C36006566c9036d2cD9AA99960",
    featured: false,
    status: "Testnet",
    date: "2024",
  },
  {
    id: "fann-sep-auction-marketplace",
    name: "Auction Marketplace (Testnet)",
    project: "FANN ArtTech",
    category: "RWA Infrastructure",
    network: "Sepolia Testnet",
    networkColor: "#45E3D3",
    chain: "Sepolia",
    type: "Auction Contract",
    description: "Testnet auction contract for end-to-end QA of FANN's art auction flows, bid management, and settlement logic.",
    address: "0xefbc922a387fa3341956a56b2A8e77412434C183",
    shortAddress: "0xefbc...C183",
    url: "https://sepolia.etherscan.io/address/0xefbc922a387fa3341956a56b2A8e77412434C183",
    featured: false,
    status: "Testnet",
    date: "2024",
  },
  {
    id: "fann-sep-identity",
    name: "Identity Registry (Testnet)",
    project: "FANN ArtTech",
    category: "Compliance & KYC",
    network: "Sepolia Testnet",
    networkColor: "#45E3D3",
    chain: "Sepolia",
    type: "Identity Registry",
    description: "Sepolia testnet identity registry for validating ERC-3643 compliance flows. Maps wallets to verified DID claims for pre-production testing.",
    address: "0xcED3aBaD2EDD59DEdDf2150f416C38c4b84fC519",
    shortAddress: "0xcED3...C519",
    url: "https://sepolia.etherscan.io/address/0xcED3aBaD2EDD59DEdDf2150f416C38c4b84fC519",
    featured: false,
    status: "Testnet",
    date: "2024",
  },
  {
    id: "fann-sep-kyc",
    name: "KYC Registry (Testnet)",
    project: "FANN ArtTech",
    category: "Compliance & KYC",
    network: "Sepolia Testnet",
    networkColor: "#45E3D3",
    chain: "Sepolia",
    type: "KYC Module",
    description: "Testnet KYC verification registry for FANN. Stores hashed claim data against investor identities for staging compliance testing.",
    address: "0xBd4bfA2E111201bFbf5534185f4D82A4Bd250937",
    shortAddress: "0xBd4b...0937",
    url: "https://sepolia.etherscan.io/address/0xBd4bfA2E111201bFbf5534185f4D82A4Bd250937",
    featured: false,
    status: "Testnet",
    date: "2024",
  },
  {
    id: "fann-sep-compliance",
    name: "Modular Compliance (Testnet)",
    project: "FANN ArtTech",
    category: "Compliance & KYC",
    network: "Sepolia Testnet",
    networkColor: "#45E3D3",
    chain: "Sepolia",
    type: "Compliance Engine",
    description: "Testnet compliance engine for the FANN platform. Validates modular rule sets including transfer caps, holding limits, and country restrictions.",
    address: "0xFDF8400fcc0E7C0e196b76CB22094f9E19971F5e",
    shortAddress: "0xFDF8...1F5e",
    url: "https://sepolia.etherscan.io/address/0xFDF8400fcc0E7C0e196b76CB22094f9E19971F5e",
    featured: false,
    status: "Testnet",
    date: "2024",
  },
  {
    id: "fann-sep-sale-escrow",
    name: "Sale Escrow (Testnet)",
    project: "FANN ArtTech",
    category: "RWA Infrastructure",
    network: "Sepolia Testnet",
    networkColor: "#45E3D3",
    chain: "Sepolia",
    type: "Escrow Contract",
    description: "Testnet escrow contract for fixed-price RWA sales. Used for full-cycle integration testing of the FANN sale flow.",
    address: "0xaAf930091d892B21AdCdf85C9efCBA45758E5627",
    shortAddress: "0xaAf9...5627",
    url: "https://sepolia.etherscan.io/address/0xaAf930091d892B21AdCdf85C9efCBA45758E5627",
    featured: false,
    status: "Testnet",
    date: "2024",
  },
  {
    id: "fann-sep-auction-escrow",
    name: "Auction Escrow (Testnet)",
    project: "FANN ArtTech",
    category: "RWA Infrastructure",
    network: "Sepolia Testnet",
    networkColor: "#45E3D3",
    chain: "Sepolia",
    type: "Escrow Contract",
    description: "Testnet auction escrow contract. Locks bidder funds during live auctions and releases to seller on completion.",
    address: "0xa743AFBAabEC96f783161150101Feb477FC40A18",
    shortAddress: "0xa743...0A18",
    url: "https://sepolia.etherscan.io/address/0xa743AFBAabEC96f783161150101Feb477FC40A18",
    featured: false,
    status: "Testnet",
    date: "2024",
  },
  {
    id: "fann-sep-mock-usdt",
    name: "Mock USDT (Testnet)",
    project: "FANN ArtTech",
    category: "Token Contracts",
    network: "Sepolia Testnet",
    networkColor: "#45E3D3",
    chain: "Sepolia",
    type: "ERC-20 Token",
    description: "Mock USDT token for FANN testnet environment. Mimics USD₮ behaviour for end-to-end payment flow testing without real funds.",
    address: "0x37fB62b921B087F0826577fD86c945972bcF7467",
    shortAddress: "0x37fB...C467",
    url: "https://sepolia.etherscan.io/address/0x37fB62b921B087F0826577fD86c945972bcF7467",
    featured: false,
    status: "Testnet",
    date: "2024",
  },

  // ── Additional Sepolia / Testnet Contracts ──────────────────
  {
    id: "rwa-auction-sep",
    name: "Upgradeable RWA Auction",
    project: "Client / FANN",
    category: "RWA Infrastructure",
    network: "Sepolia Testnet",
    networkColor: "#45E3D3",
    chain: "Sepolia",
    type: "Upgradeable Contract",
    description: "UUPS upgradeable auction contract for tokenized real-world assets. Supports proxy-pattern upgrades for future feature additions.",
    address: "0x3e2223ee75917bab6cca212aacd60fc8392af252",
    shortAddress: "0x3e22...f252",
    url: "https://sepolia.etherscan.io/address/0x3e2223ee75917bab6cca212aacd60fc8392af252#code",
    featured: false,
    status: "Testnet",
    date: "2024",
  },
  {
    id: "rwa-escrow-sep",
    name: "Upgradeable RWA Escrow",
    project: "Client / FANN",
    category: "RWA Infrastructure",
    network: "Sepolia Testnet",
    networkColor: "#45E3D3",
    chain: "Sepolia",
    type: "Upgradeable Contract",
    description: "UUPS upgradeable escrow for RWA transactions with multi-party release conditions and dispute resolution hooks.",
    address: "0x0265f1ab58feaf2082204e8bd53c448fa6ad76ec",
    shortAddress: "0x0265...76ec",
    url: "https://sepolia.etherscan.io/address/0x0265f1ab58feaf2082204e8bd53c448fa6ad76ec#code",
    featured: false,
    status: "Testnet",
    date: "2024",
  },
  {
    id: "rwa-sale-sep",
    name: "Upgradeable RWA Sale",
    project: "Client / FANN",
    category: "RWA Infrastructure",
    network: "Sepolia Testnet",
    networkColor: "#45E3D3",
    chain: "Sepolia",
    type: "Upgradeable Contract",
    description: "Direct sale contract for tokenized real-world assets using the UUPS upgrade pattern for post-deployment modifications.",
    address: "0xab2998d91a5157320870a47cdb73ecdfcd04de61",
    shortAddress: "0xab29...de61",
    url: "https://sepolia.etherscan.io/address/0xab2998d91a5157320870a47cdb73ecdfcd04de61#code",
    featured: false,
    status: "Testnet",
    date: "2024",
  },
  {
    id: "nft-marketplace-sep",
    name: "Upgradeable NFT Marketplace",
    project: "Client Project",
    category: "NFT & Marketplace",
    network: "Sepolia Testnet",
    networkColor: "#45E3D3",
    chain: "Sepolia",
    type: "Upgradeable Marketplace",
    description: "Full-featured NFT marketplace on Sepolia testnet with upgradeability. Supports fixed-price sales, auction mechanics, and batch operations.",
    address: "0xa95c517169751a434d5c3b6111404e0c18775efe",
    shortAddress: "0xa95c...5efe",
    url: "https://sepolia.etherscan.io/address/0xa95c517169751a434d5c3b6111404e0c18775efe#code",
    featured: false,
    status: "Testnet",
    date: "2023",
  },
  {
    id: "p2p-escrow-sep",
    name: "1-to-1 P2P Escrow",
    project: "Client Project",
    category: "NFT & Marketplace",
    network: "Sepolia Testnet",
    networkColor: "#45E3D3",
    chain: "Sepolia",
    type: "Escrow Contract",
    description: "Trustless peer-to-peer escrow contract for direct NFT/token trades without intermediaries. Both parties deposit assets; release is atomic.",
    address: "0xdfe9379f507ae616fcc71d7227ccac6893828f73",
    shortAddress: "0xdfe9...8f73",
    url: "https://sepolia.etherscan.io/address/0xdfe9379f507ae616fcc71d7227ccac6893828f73#code",
    featured: false,
    status: "Testnet",
    date: "2023",
  },
  {
    id: "invoice-sep",
    name: "Invoice & Payment Contract",
    project: "Client Project",
    category: "Payments & Finance",
    network: "Sepolia Testnet",
    networkColor: "#45E3D3",
    chain: "Sepolia",
    type: "Payment Contract",
    description: "On-chain invoice management system. Creates, tracks, and settles invoices using stablecoin payments with dispute and partial-payment support.",
    address: "0x5fdc94ff32f8a486dc55283043338c6242374745",
    shortAddress: "0x5fdc...4745",
    url: "https://sepolia.etherscan.io/address/0x5fdc94ff32f8a486dc55283043338c6242374745#code",
    featured: false,
    status: "Testnet",
    date: "2023",
  },
  {
    id: "sepolia-contract-main",
    name: "Sepolia Main Contract",
    project: "Client Project",
    category: "NFT & Marketplace",
    network: "Sepolia Testnet",
    networkColor: "#45E3D3",
    chain: "Sepolia",
    type: "Smart Contract",
    description: "Production-ready contract deployed on Sepolia for client final testing. Covers token transfer logic, access control, and multi-sig ownership.",
    address: "0x305680000285A098f6A464250de28147139b0473",
    shortAddress: "0x3056...0473",
    url: "https://sepolia.etherscan.io/address/0x305680000285A098f6A464250de28147139b0473",
    featured: false,
    status: "Testnet",
    date: "2024",
  },

  // ── BSC Testnet ───────────────────────────────────────────
  {
    id: "bsc-testnet-contract",
    name: "BSC Testnet Contract",
    project: "Client Project",
    category: "DeFi & DEX",
    network: "BSC Testnet",
    networkColor: "#C9A655",
    chain: "BSC Testnet",
    type: "Test Deployment",
    description: "Testnet contract on BNB Chain for staging DeFi logic. Used for integration testing of swap, staking, and yield distribution flows.",
    address: "0x2Ff598aaAb89aa39dfe597a9546a4d9B9F6a8B99",
    shortAddress: "0x2Ff5...8B99",
    url: "https://testnet.bscscan.com/address/0x2Ff598aaAb89aa39dfe597a9546a4d9B9F6a8B99",
    featured: false,
    status: "Testnet",
    date: "2023",
  },
];

// ─── EXPERIENCE ───────────────────────────────────────────────
export const EXPERIENCE = [
  {
    id: "ventram",
    role: "Co-Founder & CTO",
    company: "VentraM Group",
    period: "Jan 2025 – Present",
    location: "Doha, Qatar · On-site",
    type: "Full-time",
    current: true,
    description:
      "Co-founding VentraM Group — a GCC-first venture studio dedicated to building, launching, and scaling high-growth technology startups across Web3, SaaS, and ArtTech verticals in the MENA region.",
    achievements: [
      "Co-founded and lead technology strategy for a GCC-first venture studio",
      "Architect and oversee technical infrastructure across portfolio ventures",
      "Established scalable frameworks for rapid product development and deployment across the GCC",
    ],
    skills: ["Venture Building", "Technology Leadership", "Product Architecture", "Web3", "SaaS", "Team Building"],
    flagship: null,
  },
  {
    id: "fann-cto",
    role: "Chief Technology Officer",
    company: "FANN",
    period: "Oct 2023 – Present",
    location: "Doha, Qatar · On-site",
    type: "Full-time · On-site",
    current: true,
    description:
      "Leading development of a blockchain-native ArtTech platform transforming how physical and digital art is authenticated, valued, and traded globally. Joined alongside NFTyART from Oct 2023, transitioning full-time as FANN scaled.",
    achievements: [
      "Architected the full technical stack: blockchain authentication, AI-powered valuation systems, AR/VR gallery components, and fractional ownership models",
      "Built and managed cross-functional teams across product design, engineering, AI/ML, marketing, and operations",
      "Delivered investor-ready MVP infrastructure and scalable product architecture",
    ],
    skills: ["Technology Leadership", "Blockchain Architecture", "AI/ML", "Solidity", "Web3", "React", "Node.js"],
    flagship: { name: "FANN", url: "https://fann.art", label: "Product" },
    extraRole: {
      role: "Leadership Representative",
      period: "Jan 2025 – Present",
      description: "Representing FANN at major global tech conferences — building strategic partnerships and positioning FANN as a globally recognised ArtTech ecosystem.",
      achievements: [
        "Represented FANN at Web Summit Qatar, STEP Dubai, and LEAP Riyadh",
        "Built strategic partnerships across global tech and art communities",
        "Positioned FANN as a scalable, globally recognised ArtTech ecosystem",
      ],
      skills: ["Public Speaking", "Strategic Partnerships", "Business Development", "ArtTech"],
    },
  },
  {
    id: "nftyart",
    role: "Blockchain Developer & Technical Lead",
    company: "NFTyART",
    period: "Feb 2023 – Mar 2024",
    location: "Kuwait · Hybrid",
    type: "Full-time · Hybrid",
    current: false,
    description:
      "Designed and deployed smart contracts powering the NFTyART marketplace, leading the blockchain development lifecycle and coordinating cross-functional technical teams.",
    achievements: [
      "Designed and deployed smart contracts powering NFTyART marketplace functionality",
      "Led the blockchain development lifecycle and coordinated cross-functional technical teams",
      "Delivered scalable Web3 integrations and smart contract infrastructure",
    ],
    skills: ["Solidity", "Smart Contracts", "Web3", "NFTs", "Ethereum", "Project Management"],
    flagship: null,
  },
  {
    id: "techifort-blockchain",
    role: "Blockchain Developer",
    company: "Techifort",
    period: "Jun 2022 – Feb 2023",
    location: "Lahore, Pakistan · On-site",
    type: "Full-time · On-site",
    current: false,
    description:
      "Transitioned from full-stack development into blockchain engineering — building smart contracts, Web3 integrations, and decentralised application modules using Solidity and Ethereum.",
    achievements: [
      "Transitioned from MERN Stack into blockchain engineering within the same team",
      "Built smart contracts and Web3 integrations using Solidity, Ethereum, and Node.js",
      "Delivered decentralised application modules and blockchain architecture components",
    ],
    skills: ["Solidity", "Ethereum", "Web3.js", "Node.js", "Smart Contracts", "DApps"],
    flagship: null,
    extraRole: {
      role: "MERN Stack Developer",
      period: "Aug 2021 – Jun 2022",
      current: false,
      description: "Joined Techifort as a full-stack engineer, building scalable web platforms using the MERN stack before transitioning into blockchain development.",
      achievements: [
        "Built scalable web platforms using React, Node.js, Express, and MongoDB",
        "Developed secure REST APIs and responsive, performant user interfaces",
      ],
      skills: ["React", "Node.js", "Express", "MongoDB", "REST APIs", "JavaScript", "TypeScript"],
    },
  },
  {
    id: "freelance",
    role: "Freelance Web3 & Full-Stack Developer",
    company: "Self-Employed",
    period: "Jan 2019 – Dec 2024",
    location: "Remote · Global",
    type: "Freelance",
    current: false,
    description:
      "Delivered 60+ global projects across Web3, blockchain infrastructure, smart contracts, and full-stack platforms for clients across the US, Europe, and GCC.",
    achievements: [
      "Delivered 60+ projects across Web3, blockchain infrastructure, smart contracts, and full-stack platforms",
      "Built decentralised applications, NFT marketplaces, DeFi tools, and SaaS platforms",
      "Served clients across the US, Europe, and GCC markets",
    ],
    skills: ["Solidity", "Smart Contracts", "React", "Node.js", "Web3", "DeFi", "NFTs", "Full-Stack"],
    flagship: null,
  },
  {
    id: "mca",
    role: "Engineer Intern",
    company: "MCA Education System",
    period: "Dec 2018 – Dec 2019",
    location: "Peshawar, Pakistan",
    type: "Internship",
    current: false,
    description:
      "Gained hands-on experience in networking, system administration, and IT operations — the foundation of a technical career.",
    achievements: [
      "Gained practical experience in networking, system administration, and IT operations",
      "Installed, configured, and maintained IT infrastructure including servers and network systems",
    ],
    skills: ["IT Operations", "Networking", "System Administration", "HTML", "CSS"],
    flagship: null,
  },
];

// ─── SKILLS ───────────────────────────────────────────────────
export const SKILL_GROUPS = [
  {
    category: "Blockchain & Web3",
    color: "gold",
    proficiency: 98,
    skills: ["Solidity", "TypeScript", "Hardhat", "Truffle", "Ethers.js", "Web3.js", "OpenZeppelin", "ERC Standards"],
  },
  {
    category: "DeFi & DApp Development",
    color: "teal",
    proficiency: 95,
    skills: ["React", "Next.js", "Solidity", "Web3.js", "Ethers.js", "DeFi Protocols", "Smart Contracts"],
  },
  {
    category: "Full-Stack (MERN)",
    color: "indigo",
    proficiency: 95,
    skills: ["JavaScript", "TypeScript", "React", "Next.js 14/15", "Express", "Node.js", "Redux/RTK", "Tailwind CSS"],
  },
  {
    category: "Backend & APIs",
    color: "violet",
    proficiency: 90,
    skills: ["Node.js", "Express.js", "RESTful APIs", "GraphQL", "PostgreSQL", "MongoDB", "Redis"],
  },
  {
    category: "AI & Machine Learning",
    color: "emerald",
    proficiency: 75,
    skills: ["Python", "TensorFlow", "Computer Vision", "AI/ML Integration", "Data Analytics"],
  },
  {
    category: "Infrastructure & DevOps",
    color: "teal",
    proficiency: 80,
    skills: ["IPFS", "Docker", "Vercel", "Netlify", "Git", "GitHub Actions", "Linux"],
  },
];

// ─── ARTICLES ─────────────────────────────────────────────────
export const ARTICLES = [
  {
    id: "nftyart-to-fann",
    title: "NFTyART to FANN: Building a Hybrid NFT Marketplace for Digital & Physical Art",
    excerpt:
      "From NFTyART's niche digital marketplace to FANN's revolutionary hybrid platform bridging physical artwork with NFTs. A comprehensive look at building scalable Web3 infrastructure.",
    date: "June 3, 2025",
    readTime: "18 min read",
    tags: ["NFT", "Blockchain", "Marketplace", "Web3"],
    url: "https://medium.com/@sabilkhattak77/nftyart-to-fann-building-a-hybrid-nft-marketplace-for-digital-physical-art-d538b8310152",
    featured: true,
  },
  {
    id: "future-of-art",
    title: "The Future of Art: Powered by Blockchain and Emerging Technologies",
    excerpt:
      "Art is transforming through intelligent code, augmented reality, and cryptographic signatures. Exploring the next decade of creative economies.",
    date: "May 19, 2025",
    readTime: "5 min read",
    tags: ["Blockchain", "Art", "Technology"],
    url: "https://medium.com/@sabilkhattak77/the-future-of-art-powered-by-blockchain-and-emerging-technologies-95a15222b541",
    featured: false,
  },
  {
    id: "beyond-crypto",
    title: "Beyond Crypto — How Blockchain is Revolutionizing Industries",
    excerpt:
      "Blockchain isn't just disrupting finance — it's quietly rewriting the rules of healthcare, supply chain, and everyday life.",
    date: "December 15, 2024",
    readTime: "8 min read",
    tags: ["Blockchain", "Healthcare", "Supply Chain", "Innovation"],
    url: "https://www.linkedin.com/pulse/edition-03-beyond-crypto-how-blockchain-industries-you-sabil-ahmad-z0wqf/",
    featured: false,
  },
  {
    id: "web3-architecture",
    title: "Building Resilient Web3 Architecture: Lessons from the Field",
    excerpt:
      "Technical insights from building production-ready DApps. Best practices for smart contract security, scalability, and developer velocity.",
    date: "November 20, 2024",
    readTime: "12 min read",
    tags: ["Web3", "Smart Contracts", "Architecture"],
    url: "https://www.linkedin.com/newsletters/7242043917003616256/",
    featured: false,
  },
];

// ─── ABOUT PILLARS ────────────────────────────────────────────
export const PILLARS = [
  {
    icon: "🔐",
    title: "Security & Auditability",
    description: "Smart contracts that audit clean — formal verification, comprehensive testing, zero shortcuts.",
  },
  {
    icon: "⚡",
    title: "Scalability",
    description: "High-performance architectures designed for millions of users and transactions from day one.",
  },
  {
    icon: "🔗",
    title: "Token Standards Mastery",
    description: "Expert implementation of ERC-20, 721, 1155, 4626, and complex tokenization scenarios.",
  },
  {
    icon: "📊",
    title: "Data-Driven Design",
    description: "Analytics-first architecture enabling real-time insights, not post-hoc reporting.",
  },
  {
    icon: "🚀",
    title: "Developer Velocity",
    description: "Modern tooling and practices that make teams fast, reliable, and impossible to slow down.",
  },
];

// ─── PROJECT CATEGORIES ───────────────────────────────────────
export const PROJECT_CATEGORIES = [
  "All",
  "DeFi & Tokenisation",
  "NFT Marketplaces",
  "DApps & GameFi",
  "Blockchain & Web3",
  "Launchpads & GameFi",
  "Logistics & Supply Chain",
];
